### ISSUE TITLE
How can I run this on a local machine?

### ISSUE THREAD

**Issue by rmohta** [ritz078/transform#180]
I'm assumed it's possible to run this on my laptop, and did the following steps. Can someone help me understand what am I doing wrong here?

Steps:
- Use nvm to install node v10.20.1
- npm install -g next react react-dom
- next --version 
Output: Next.js v9.3.6
- npm i

I have tried to run the code using
* _npm run-script build_
* _next build_

```
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

> Using external babel configuration
> Location: "/home/rohitmohta/git/transform/.babelrc"
Creating an optimized production build ..
<--- Last few GCs --->
...
...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x8fb090 node::Abort() [/home/rohitmohta/.nvm/versions/node/v10.20.1/bin/node]
 2: 0x8fb0dc  [/home/rohitmohta/.nvm/versions/node/v10.20.1/bin/node]
...
Creating an optimized production build ..

```
It's was stuck in the last line for almost 25mins.

* _next dev_
This fails with the below error

```
/home/rohitmohta/git/transform/node_modules/@babel/runtime-corejs2/helpers/esm/objectSpread.js:1
import _Object$getOwnPropertyDescriptor from "../../core-js/object/get-own-property-descriptor";
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.@babel/runtime-corejs2/helpers/esm/objectSpread (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:5138:18)
    at __webpack_require__ (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:23:31)
    at Module../pages/_document.tsx (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:4939:105)
    at __webpack_require__ (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:23:31)
    at Object.1 (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:5126:18)
    at __webpack_require__ (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:23:31)
    at module.exports.../../.nvm/versions/node/v10.20.1/lib/node_modules/next/dist/pages/_document.js.exports.__esModule (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:91:18)
    at Object.<anonymous> (/home/rohitmohta/git/transform/.next/server/static/development/pages/_document.js:94:10)

```

OS Details: Linux Fedora 5.5.17-200.fc31.x86_64 with 16GB RAM

**Comment by ritz078** [comment]
I will work on the weekend to fix these issues. It is mostly because monaco-editor takes a lot of time to build. I will try to separate that component and distribute an already built bundle on npm.

**Comment by ritz078** [comment]
Can you try running `yarn dev` using the latest master ?
